version: '3.9'

services:
  api:
    build:
      context: ./api
      dockerfile: api.Dockerfile
    container_name: fastapi_api
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    depends_on: 
      - db
    command: uvicorn server:app --host 0.0.0.0 --port 8000
    env_file:
      - .env

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${USUARIO_POSTGRES}
      POSTGRES_PASSWORD: ${SENHA_POSTGRES}
      POSTGRES_DB: ${DB_POSTGRES}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env

  front:
    build:
      context: ./front/analizador-nf
      dockerfile: front.Dockerfile
    container_name: react_frontend
    ports:
      - "8080:8080"
    depends_on:
      - api

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${USUARIO_PGADMIN}
      PGADMIN_DEFAULT_PASSWORD: ${SENHA_PGADMIN}
    ports:
      - "5050:80"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data: