version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    container_name: fastapi_api
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    depends_on: []
    command: uvicorn server:app --host 0.0.0.0 --port 8000
