swagger: "2.0"
info:
  title: api-avaliacao
  description: "API desenvolvida utilizando FastAPI que integra a API do Gemini para recuperar campos de notas fiscais."
  version: "1.0.0"
schemes:
  - "https"
paths:
  "/":
    get:
      description: "Retorna todos os dados de nota fiscal do banco de dados postgres"
      operationId: "get"
      responses:
        200:
          description: "Success."
          schema:
            type: string
      x-google-backend:
        address: https://us-central1-sapient-flight-465213-n9.cloudfunctions.net/get-avaliacao
        protocol: h2
      x-google-extensions:
        cors:
          allowOrigins: ["*"]
          allowMethods: ["GET", "OPTIONS"]
          allowHeaders: ["*"]

  "/notas":
    post:
      description: "Função destinada para envio de arquivo / processamento via Gemini dos mesmos"
      operationId: "post"
      responses:
        200:
          description: "Success."
          schema:
            type: string
      x-google-backend:
        address: https://us-central1-sapient-flight-465213-n9.cloudfunctions.net/post-avaliacao
        protocol: h2
      x-google-extensions:
        cors:
          allowOrigins: ["*"]
          allowMethods: ["POST", "OPTIONS"]
          allowHeaders: ["*"]

    delete:
      description: "Função que tem o objetivo de deletar uma linha da tabela notas"
      operationId: "delete"
      responses:
        200:
          description: "Success."
          schema:
            type: string
      x-google-backend:
        address: https://us-central1-sapient-flight-465213-n9.cloudfunctions.net/delete-avaliacao
        protocol: h2
      x-google-extensions:
        cors:
          allowOrigins: ["*"]
          allowMethods: ["DELETE", "OPTIONS"]
          allowHeaders: ["*"]

    options:
      operationId: "options"
      description: "Preflight CORS para /notas"
      responses:
        204:
          description: "CORS preflight success."
      x-google-backend:
        address: https://us-central1-sapient-flight-465213-n9.cloudfunctions.net/delete-avaliacao
        protocol: h2
      x-google-extensions:
        cors:
          allowOrigins: ["*"]
          allowMethods: ["DELETE", "OPTIONS"]
          allowHeaders: ["*"]