swagger: "2.0"
info:
  title: api-avaliacao
  description: "API desenvolvida utilizando FastAPI que integra a API do Gemini para recuperar campos de notas fiscais."
  version: "1.0.0"
schemes:
  - "https"
paths:
  "/":
    get:
      description: "Retorna todos os dados de nota fiscal do banco de dados postgres"
      operationId: "get"
      responses:
        200:
          description: "Success."
          schema:
            type: string
      x-google-backend:
        address: https://get-avaliacao-314988402732.europe-west1.run.app
        protocol: h2
  "/notas":
    post:
      description: "Função destinada para envio de arquivo / processamento via Gemini dos mesmos"
      operationId: "post"
      responses:
        200:
          description: "Success."
          schema:
            type: string
      x-google-backend:
        address: https://post-avaliacao-314988402732.europe-west1.run.app
        protocol: h2
    delete:
      description: "Função que tem o objetivo de deletar uma linha da tabela notas"
      operationId: "delete"
      responses:
        200:
          description: "Success."
          schema:
            type: string
      x-google-backend:
        address: https://delete-avaliacao-314988402732.europe-west1.run.app
        protocol: h2