name: Deploy React App to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Autenticar no GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configurar Docker pro Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build da imagem Docker
        run: |
          docker build -f front/analizador-nf/front.Dockerfile -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/avaliacao-repo/front:latest ./front/analizador-nf

      - name: Push da imagem pro Artifact Registry
        run: |
          docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/avaliacao-repo/front:latest

      - name: Deploy no Cloud Run
        run: |
          gcloud run deploy front-app \
            --image=us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/avaliacao-repo/front:latest \
            --region=us-central1 \
            --platform=managed \
            --allow-unauthenticated \
            --project=${{ secrets.GCP_PROJECT_ID }}
